---
title: "Objectives"

bibliography: references/references.bib
link-citations: TRUE
---

{{< pagebreak >}}

This is a draft write up that aims to provide examples of ways auxiliary
data can be used to inform the speciation of sonar fish imaging data.
This is part of an ongoing effort by the California (Coastal) Monitoring
Plan (CMP) Sonar Subgroup to provide support to survey efforts using
sonar to estimate abundances of migrating adult salmonids. Often
distinguishing species for a given fish using a sonar image can be
difficult due to images that are low-resolution and at an angle that
makes identification difficult. The difficulty of accurate speciation
can be compounded in systems when many different species are present at
the same time, especially if those fish are of similar size classes and
produce similar acoustic profiles.

I do not aim to provide a "blanket" method for species apportionment
that can be applied to all sonar imaging studies. Each watershed is
different, and has different auxiliary data available for use. Also, the
methods detailed do not aim to replace visual identifications made by
scientists with local knowledge and identification experience. Instead,
this document will provide examples of statistical methods that can
utilize auxiliary data to aid in assigning species identifications to
sonar movement data where visual identification is not possible. Some of
these methods have been briefly described in @Atkinson2016, and I hope
the following methodology provides additional helpful detail on how to
implement the techniques.

We will begin with the most simple methods, incorporating the barest of
auxiliary data sets, and build upon those with increasingly more complex
methods and data sets. Hopefully by the end, the reader can better
evaluate how to tackle their sonar imaging data and what auxiliary data
they can use to increase the accuracy of species apportionment.

This will be a "living" document, with continues updates and edits being
made while we continue to explore and test various speciation methods.
Throughout this document, various chunks of R code will be presented in
the following format:

```{r, example chunk}
print("hello reader")
```

These chunks are designed for users to copy and paste, or rewrite
entirely, into their own R scripts to replicate the methods.

{{< pagebreak >}}
